version: "3.1"

services:
  challenge-api:
    image: challenge-api-image:latest
    container_name: challenge-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /data/spring-boot-app